package com.sw.bi.scheduler.model;

// Generated 2011-12-19 14:42:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * Action generated by hbm2java
 */
public class Action implements java.io.Serializable {

	private long actionId;
	private long taskId;
	private long jobId;
	private Long jobType;
	private Date settingTime;
	private Date startTime;
	private Date endTime;
	private int actionStatus;
	private String jobName;
	private int cycleType;
	private Date taskDate;
	private Date scanDate;
	private String actionLog;
	private String operator;
	private String gateway;
	private int flag;
	private Date createTime;
	private Date updateTime;
	private Set<ActionSql> actionSqls;

	public Action() {}

	public Action(long actionId, long taskId, long jobId, Date startTime, int actionStatus, String jobName, Date taskDate, String operator, String gateway, int flag, Date createTime) {
		this.actionId = actionId;
		this.taskId = taskId;
		this.jobId = jobId;
		this.startTime = startTime;
		this.actionStatus = actionStatus;
		this.jobName = jobName;
		this.taskDate = taskDate;
		this.operator = operator;
		this.gateway = gateway;
		this.flag = flag;
		this.createTime = createTime;
	}

	public Action(long actionId, long taskId, long jobId, Date startTime, Date endTime, int actionStatus, String jobName, Date taskDate, String actionLog, String operator, String gateway, int flag,
			Date createTime, Date updateTime) {
		this.actionId = actionId;
		this.taskId = taskId;
		this.jobId = jobId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.actionStatus = actionStatus;
		this.jobName = jobName;
		this.taskDate = taskDate;
		this.actionLog = actionLog;
		this.operator = operator;
		this.gateway = gateway;
		this.flag = flag;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public long getActionId() {
		return this.actionId;
	}

	public void setActionId(long actionId) {
		this.actionId = actionId;
	}

	public long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(long taskId) {
		this.taskId = taskId;
	}

	public long getJobId() {
		return this.jobId;
	}

	public void setJobId(long jobId) {
		this.jobId = jobId;
	}

	public Date getSettingTime() {
		return settingTime;
	}

	public void setSettingTime(Date settingTime) {
		this.settingTime = settingTime;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public int getActionStatus() {
		return this.actionStatus;
	}

	public void setActionStatus(int actionStatus) {
		this.actionStatus = actionStatus;
	}

	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public int getCycleType() {
		return cycleType;
	}

	public void setCycleType(int cycleType) {
		this.cycleType = cycleType;
	}

	public Date getTaskDate() {
		return this.taskDate;
	}

	public void setTaskDate(Date taskDate) {
		this.taskDate = taskDate;
	}

	public String getActionLog() {
		return this.actionLog;
	}

	public void setActionLog(String actionLog) {
		this.actionLog = actionLog;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getGateway() {
		return this.gateway;
	}

	public void setGateway(String gateway) {
		this.gateway = gateway;
	}

	public int getFlag() {
		return this.flag;
	}

	public void setFlag(int flag) {
		this.flag = flag;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public void setActionSqls(Set<ActionSql> actionSqls) {
		this.actionSqls = actionSqls;
	}

	public Set<ActionSql> getActionSqls() {
		return actionSqls;
	}

	public Long getJobType() {
		return jobType;
	}

	public void setJobType(Long jobType) {
		this.jobType = jobType;
	}

	public Date getScanDate() {
		return scanDate;
	}

	public void setScanDate(Date scanDate) {
		this.scanDate = scanDate;
	}

}
