package com.sw.bi.scheduler.model;

// Generated 2011-12-19 14:42:39 by Hibernate Tools 3.4.0.CR1

import org.apache.commons.beanutils.ConvertUtils;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.springframework.util.StringUtils;

import java.util.*;

/**
 * Job generated by hbm2java
 */
@JsonIgnoreProperties(value = { "hibernateLazyInitializer" })
public class Job implements java.io.Serializable, AuthenticationUserGroup {

	private long jobId;
	private String jobName;
	private String jobDesc;
	private String jobBusinessGroup;
	private String programPath;
	private String parameters;
	private long dutyOfficer;
	private long jobStatus;
	private long cycleType;
	private Long dayN;
	private String jobTime;
	private String endTime;
	private long jobLevel;
	private long alert;
	private long jobType;
	private String downReason;
	private Date downTime;
	private Long downMan;
	private String gateway;
	private Date createTime;
	private Date updateTime;
	private Long updateBy;
	private Integer failureRerunTimes; // 作业失败重跑次数
	private Integer failureRerunInterval; // 作业失败重跑间隔时长(分钟)

	private Set<Task> tasks = new HashSet<Task>(0);

	/**
	 * 前置作业，用于生成前置任务(天作业只允许前置天作业，周只允许周，月只允许月)
	 */
	private String prevJobs;

	/**
	 * 数据源用途
	 */
	private String dataSourceUse;

	/**
	 * 责任人所属用户组
	 */
	private UserGroup userGroup;

	public Job() {
		
	}

	public Job(long jobId, String jobName, String programPath, long dutyOfficer, long jobStatus, long cycleType, long jobLevel, long alert, String output, long jobType, Date createTime) {
		this.jobId = jobId;
		this.jobName = jobName;
		this.programPath = programPath;
		this.dutyOfficer = dutyOfficer;
		this.jobStatus = jobStatus;
		this.cycleType = cycleType;
		this.jobLevel = jobLevel;
		this.alert = alert;
		this.jobType = jobType;
		this.createTime = createTime;
	}

	public Job(long jobId, String jobName, String jobDesc, String jobBusinessGroup, String programPath, String parameters, long dutyOfficer, long jobStatus, long cycleType, Long dayN, String jobTime,
			long jobLevel, long alert, String output, long jobType, String downReason, Date downTime, Long downMan, Date createTime, Date updateTime, Set<Task> tasks) {
		this.jobId = jobId;
		this.jobName = jobName;
		this.jobDesc = jobDesc;
		this.jobBusinessGroup = jobBusinessGroup;
		this.programPath = programPath;
		this.parameters = parameters;
		this.dutyOfficer = dutyOfficer;
		this.jobStatus = jobStatus;
		this.cycleType = cycleType;
		this.dayN = dayN;
		this.jobTime = jobTime;
		this.jobLevel = jobLevel;
		this.alert = alert;
		this.jobType = jobType;
		this.downReason = downReason;
		this.downTime = downTime;
		this.downMan = downMan;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.tasks = tasks;
	}

	public long getJobId() {
		return this.jobId;
	}

	public void setJobId(long jobId) {
		this.jobId = jobId;
	}

	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public String getJobDesc() {
		return this.jobDesc;
	}

	public void setJobDesc(String jobDesc) {
		this.jobDesc = jobDesc;
	}

	public String getJobBusinessGroup() {
		return this.jobBusinessGroup;
	}

	public void setJobBusinessGroup(String jobBusinessGroup) {
		this.jobBusinessGroup = jobBusinessGroup;
	}

	public String getProgramPath() {
		return this.programPath;
	}

	public void setProgramPath(String programPath) {
		this.programPath = programPath;
	}

	public String getParameters() {
		return this.parameters;
	}

	public void setParameters(String parameters) {
		this.parameters = parameters;
	}

	public long getDutyOfficer() {
		return this.dutyOfficer;
	}

	public void setDutyOfficer(long dutyOfficer) {
		this.dutyOfficer = dutyOfficer;
	}

	public long getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(long jobStatus) {
		this.jobStatus = jobStatus;
	}

	public long getCycleType() {
		return this.cycleType;
	}

	public void setCycleType(long cycleType) {
		this.cycleType = cycleType;
	}

	public Long getDayN() {
		return this.dayN;
	}

	public void setDayN(Long dayN) {
		this.dayN = dayN;
	}

	public String getJobTime() {
		return this.jobTime;
	}

	public void setJobTime(String jobTime) {
		this.jobTime = jobTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public long getJobLevel() {
		return this.jobLevel;
	}

	public void setJobLevel(long jobLevel) {
		this.jobLevel = jobLevel;
	}

	public long getAlert() {
		return this.alert;
	}

	public void setAlert(long alert) {
		this.alert = alert;
	}

	public long getJobType() {
		return this.jobType;
	}

	public void setJobType(long jobType) {
		this.jobType = jobType;
	}

	public String getDownReason() {
		return this.downReason;
	}

	public void setDownReason(String downReason) {
		this.downReason = downReason;
	}

	public Date getDownTime() {
		return this.downTime;
	}

	public void setDownTime(Date downTime) {
		this.downTime = downTime;
	}

	public Long getDownMan() {
		return this.downMan;
	}

	public void setDownMan(Long downMan) {
		this.downMan = downMan;
	}

	public String getGateway() {
		return gateway;
	}

	public void setGateway(String gateway) {
		this.gateway = gateway;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Long getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	public Integer getFailureRerunTimes() {
		return failureRerunTimes;
	}

	public void setFailureRerunTimes(Integer failureRerunTimes) {
		this.failureRerunTimes = failureRerunTimes;
	}

	public Integer getFailureRerunInterval() {
		return failureRerunInterval;
	}

	public void setFailureRerunInterval(Integer failureRerunInterval) {
		this.failureRerunInterval = failureRerunInterval;
	}

	public String getPrevJobs() {
		return prevJobs;
	}

	public void setPrevJobs(String prevJobs) {
		this.prevJobs = prevJobs;
	}

	public Long[] getPrevJobIds() {
		if (StringUtils.hasText(this.prevJobs)) {
			return (Long[]) ConvertUtils.convert(this.prevJobs.split(","), Long.class);
		}

		return null;
	}

	public String getDataSourceUse() {
		return dataSourceUse;
	}

	public void setDataSourceUse(String dataSourceUse) {
		this.dataSourceUse = dataSourceUse;
	}

	public UserGroup getUserGroup() {
		return userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

	/**
	 * 判断是否设置了依赖自己的前置作业
	 * 
	 * @return
	 */
	@JsonIgnore
	public boolean isPrevJobDependenceSelf() {
		Collection<Long> prevJobs = Arrays.asList(this.getPrevJobIds());
		return prevJobs.contains(this.getJobId());
	}

	@JsonIgnore
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

	@Override
	public String toString() {
		return "作业[作业ID: " + this.getJobId() + ", 作业名称: " + this.getJobName() + "]";
	}

	@Override
	public String getEntityName() {
		return "作业";
	}

	@Override
	public String getLoggerName() {
		return this.getJobName() + "(作业ID: " + this.getJobId() + ")";
	}

	@Override
	public Long getUserId() {
		return this.getDutyOfficer();
	}

}
