package com.sw.bi.scheduler.model;

// Generated 2012-1-9 10:47:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MethodExecTime generated by hbm2java
 */
public class MethodExecTime implements java.io.Serializable {

	private Long methodExecTimeId;
	private Date dateDesc;
	private String methodName;
	private Date beginTime;
	private Date endTime;
	private long runTime;
	private Date createTime;
	private Date updateTime;

	public MethodExecTime() {}

	public MethodExecTime(Date dateDesc, String methodName, Date beginTime, Date endTime, long runTime, Date createTime) {
		this.dateDesc = dateDesc;
		this.methodName = methodName;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.runTime = runTime;
		this.createTime = createTime;
	}

	public MethodExecTime(Date dateDesc, String methodName, Date beginTime, Date endTime, long runTime, Date createTime, Date updateTime) {
		this.dateDesc = dateDesc;
		this.methodName = methodName;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.runTime = runTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Long getMethodExecTimeId() {
		return this.methodExecTimeId;
	}

	public void setMethodExecTimeId(Long methodExecTimeId) {
		this.methodExecTimeId = methodExecTimeId;
	}

	public Date getDateDesc() {
		return this.dateDesc;
	}

	public void setDateDesc(Date dateDesc) {
		this.dateDesc = dateDesc;
	}

	public String getMethodName() {
		return this.methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public long getRunTime() {
		return this.runTime;
	}

	public void setRunTime(long runTime) {
		this.runTime = runTime;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
