package com.sw.bi.scheduler.model;

// Generated 2012-2-2 13:44:07 by Hibernate Tools 3.4.0.CR1

/**
 * Permission generated by hbm2java
 */
public class Permission implements java.io.Serializable {

	private Long permissionId;
	private Role role;
	private Resource resource;

	public Permission() {}

	public Permission(long roleId, long resourceId) {
		this.role = new Role();
		this.role.setRoleId(roleId);

		this.resource = new Resource();
		this.resource.setResourceId(resourceId);
	}

	public Long getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(Long permissionId) {
		this.permissionId = permissionId;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

}
