package com.sw.bi.scheduler.model;

// Generated 2012-3-6 16:16:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RedoAndSupplyHistory generated by hbm2java
 */
public class RedoAndSupplyHistory implements java.io.Serializable {

	private Long redoAndSupplyHistoryId;
	private String operateNo;
	private boolean isMaster;
	private Date operateDate;
	private Long operateMan;
	private int flag;
	private long taskId;
	private Long jobId;
	private String jobName;
	private Integer cycleType;
	private Long dutyMan;
	private Integer taskStatus;
	private Date settingTime;
	private Date taskDate;
	private Date beginTime;
	private Date endTime;
	private Long actionId;
	private Date createTime;
	private Date updateTime;

	private Date minTaskDate;
	private Date maxTaskDate;

	private UserGroup userGroup;
	private UserGroup operateUserGroup;

	public RedoAndSupplyHistory() {}

	public RedoAndSupplyHistory(String operateNo, boolean isMaster, Date operateDate, int flag, long taskId) {
		this.operateNo = operateNo;
		this.isMaster = isMaster;
		this.operateDate = operateDate;
		this.flag = flag;
		this.taskId = taskId;
	}

	public RedoAndSupplyHistory(String operateNo, boolean isMaster, Date operateDate, Long operateMan, int flag, long taskId, String jobName, Long dutyMan, Integer taskStatus, Date taskDate,
			Date beginTime, Date endTime, Date createTime, Date updateTime) {
		this.operateNo = operateNo;
		this.isMaster = isMaster;
		this.operateDate = operateDate;
		this.operateMan = operateMan;
		this.flag = flag;
		this.taskId = taskId;
		this.jobName = jobName;
		this.dutyMan = dutyMan;
		this.taskStatus = taskStatus;
		this.taskDate = taskDate;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Long getRedoAndSupplyHistoryId() {
		return this.redoAndSupplyHistoryId;
	}

	public void setRedoAndSupplyHistoryId(Long redoAndSupplyHistoryId) {
		this.redoAndSupplyHistoryId = redoAndSupplyHistoryId;
	}

	public String getOperateNo() {
		return this.operateNo;
	}

	public void setOperateNo(String operateNo) {
		this.operateNo = operateNo;
	}

	public boolean isIsMaster() {
		return this.isMaster;
	}

	public void setIsMaster(boolean isMaster) {
		this.isMaster = isMaster;
	}

	public Date getOperateDate() {
		return this.operateDate;
	}

	public void setOperateDate(Date operateDate) {
		this.operateDate = operateDate;
	}

	public Long getOperateMan() {
		return this.operateMan;
	}

	public void setOperateMan(Long operateMan) {
		this.operateMan = operateMan;
	}

	public int getFlag() {
		return this.flag;
	}

	public void setFlag(int flag) {
		this.flag = flag;
	}

	public long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(long taskId) {
		this.taskId = taskId;
	}

	public Long getJobId() {
		return jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public Integer getCycleType() {
		return cycleType;
	}

	public void setCycleType(Integer cycleType) {
		this.cycleType = cycleType;
	}

	public Long getDutyMan() {
		return this.dutyMan;
	}

	public void setDutyMan(Long dutyMan) {
		this.dutyMan = dutyMan;
	}

	public Integer getTaskStatus() {
		return this.taskStatus;
	}

	public void setTaskStatus(Integer taskStatus) {
		this.taskStatus = taskStatus;
	}

	public Date getSettingTime() {
		return settingTime;
	}

	public void setSettingTime(Date settingTime) {
		this.settingTime = settingTime;
	}

	public Date getTaskDate() {
		return taskDate;
	}

	public void setTaskDate(Date taskDate) {
		this.taskDate = taskDate;
	}

	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Long getActionId() {
		return actionId;
	}

	public void setActionId(Long actionId) {
		this.actionId = actionId;
	}

	public Date getMinTaskDate() {
		return minTaskDate;
	}

	public void setMinTaskDate(Date minTaskDate) {
		this.minTaskDate = minTaskDate;
	}

	public Date getMaxTaskDate() {
		return maxTaskDate;
	}

	public void setMaxTaskDate(Date maxTaskDate) {
		this.maxTaskDate = maxTaskDate;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public UserGroup getUserGroup() {
		return userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

	public UserGroup getOperateUserGroup() {
		return operateUserGroup;
	}

	public void setOperateUserGroup(UserGroup operateUserGroup) {
		this.operateUserGroup = operateUserGroup;
	}

}
