package com.sw.bi.scheduler.model;


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.Transient;
import java.util.LinkedHashSet;
import java.util.Set;

// Generated 2012-2-2 13:44:07 by Hibernate Tools 3.4.0.CR1

/**
 * Resource generated by hbm2java
 */
@JsonIgnoreProperties(value = { "hibernateLazyInitializer" })
public class Resource implements java.io.Serializable {

	private Long resourceId;
	private Resource parent;
	private String name;
	private String iconCls;
	private boolean menu;
	private Integer type;
	private String url;
	private Integer sortNo;
	private Set<Resource> children = new LinkedHashSet<Resource>();

	@Transient
	private Boolean leaf;

	public Resource() {}

	public Resource(String name, boolean menu, int type) {
		this.name = name;
		this.menu = menu;
		this.type = type;
	}

	public Resource(Resource parent, String name, String iconCls, boolean menu, Integer type, String url, Integer sortNo) {
		this.parent = parent;
		this.name = name;
		this.iconCls = iconCls;
		this.menu = menu;
		this.type = type;
		this.url = url;
		this.sortNo = sortNo;
	}

	public Long getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Long resourceId) {
		this.resourceId = resourceId;
	}

	@JsonIgnore
	public Resource getParent() {
		return this.parent;
	}

	public void setParent(Resource parent) {
		this.parent = parent;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIconCls() {
		return this.iconCls;
	}

	public void setIconCls(String iconCls) {
		this.iconCls = iconCls;
	}

	public boolean getMenu() {
		return this.menu;
	}

	public void setMenu(boolean menu) {
		this.menu = menu;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getSortNo() {
		return this.sortNo;
	}

	public void setSortNo(Integer sortNo) {
		this.sortNo = sortNo;
	}

	public Set<Resource> getChildren() {
		return children;
	}

	public void setChildren(Set<Resource> children) {
		this.children = children;
	}

	@Transient
	public String getText() {
		return name;
	}

	@Transient
	public Long getParentId() {
		Resource parent = getParent();
		return parent == null ? null : parent.getResourceId();
	}

	@Transient
	public String getParentName() {
		Resource parent = getParent();
		return parent == null ? null : parent.getName();
	}

	public boolean isLeaf() {
		Set<Resource> children = getChildren();
		return leaf == null ? (children == null ? true : children.size() == 0) : leaf;
	}

	public void setLeaf(Boolean leaf) {
		this.leaf = leaf;
	}

}
