package com.sw.bi.scheduler.model;

// Generated 2012-1-9 10:47:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SchedulerExecTimeHistory generated by hbm2java
 */
public class SchedulerExecTimeHistory implements java.io.Serializable {

	private Long schedulerExecTimeHistoryId;
	private Date dateDesc;
	private Date beginTime;
	private Date endTime;
	private Long runTime;
	private boolean finished;
	private String flag;
	private Date createTime;
	private Date updateTime;

	public SchedulerExecTimeHistory() {}

	public SchedulerExecTimeHistory(Date dateDesc, Date beginTime, boolean finished, String flag, Date createTime) {
		this.dateDesc = dateDesc;
		this.beginTime = beginTime;
		this.finished = finished;
		this.flag = flag;
		this.createTime = createTime;
	}

	public SchedulerExecTimeHistory(Date dateDesc, Date beginTime, Date endTime, Long runTime, boolean finished, String flag, Date createTime, Date updateTime) {
		this.dateDesc = dateDesc;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.runTime = runTime;
		this.finished = finished;
		this.flag = flag;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Long getSchedulerExecTimeHistoryId() {
		return this.schedulerExecTimeHistoryId;
	}

	public void setSchedulerExecTimeHistoryId(Long schedulerExecTimeHistoryId) {
		this.schedulerExecTimeHistoryId = schedulerExecTimeHistoryId;
	}

	public Date getDateDesc() {
		return this.dateDesc;
	}

	public void setDateDesc(Date dateDesc) {
		this.dateDesc = dateDesc;
	}

	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Long getRunTime() {
		return this.runTime;
	}

	public void setRunTime(Long runTime) {
		this.runTime = runTime;
	}

	public boolean isFinished() {
		return finished;
	}

	public void setFinished(boolean finished) {
		this.finished = finished;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
