package com.sw.bi.scheduler.model;

// Generated 2012-1-9 10:47:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SchedulerExecTime generated by hbm2java
 */
public class SchedulerExecTime implements java.io.Serializable {

	private Long schedulerExecTimeId;
	private Date dateDesc;
	private Date beginTime;
	private Date endTime;
	private long runTime;
	private boolean finished;
	private String flag;
	private Date createTime;
	private Date updateTime;

	public SchedulerExecTime() {}

	public SchedulerExecTime(Date dateDesc, Date beginTime, Date endTime, long runTime, boolean finished, String flag, Date createTime) {
		this.dateDesc = dateDesc;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.runTime = runTime;
		this.finished = finished;
		this.flag = flag;
		this.createTime = createTime;
	}

	public SchedulerExecTime(Date dateDesc, Date beginTime, Date endTime, long runTime, boolean finished, String flag, Date createTime, Date updateTime) {
		this.dateDesc = dateDesc;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.runTime = runTime;
		this.finished = finished;
		this.flag = flag;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Long getSchedulerExecTimeId() {
		return this.schedulerExecTimeId;
	}

	public void setSchedulerExecTimeId(Long schedulerExecTimeId) {
		this.schedulerExecTimeId = schedulerExecTimeId;
	}

	public Date getDateDesc() {
		return this.dateDesc;
	}

	public void setDateDesc(Date dateDesc) {
		this.dateDesc = dateDesc;
	}

	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public long getRunTime() {
		return this.runTime;
	}

	public void setRunTime(long runTime) {
		this.runTime = runTime;
	}

	public boolean isFinished() {
		return finished;
	}

	public void setFinished(boolean finished) {
		this.finished = finished;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
