package com.sw.bi.scheduler.model;

// Generated 2011-12-30 12:27:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TaskCreateLog generated by hbm2java
 */
public class TaskCreateLog implements java.io.Serializable {

	private Long taskCreateLogId;
	private Date taskDate;
	private Boolean createSuccess;
	private Boolean runSuccess;
	private Date createTime;
	private Date updateTime;

	public TaskCreateLog() {}

	public TaskCreateLog(Date taskDate, Date createTime) {
		this.taskDate = taskDate;
		this.createTime = createTime;
	}

	public TaskCreateLog(Date taskDate, Boolean createSuccess, Boolean runSuccess, Date createTime, Date updateTime) {
		this.taskDate = taskDate;
		this.createSuccess = createSuccess;
		this.runSuccess = runSuccess;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Long getTaskCreateLogId() {
		return this.taskCreateLogId;
	}

	public void setTaskCreateLogId(Long taskCreateLogId) {
		this.taskCreateLogId = taskCreateLogId;
	}

	public Date getTaskDate() {
		return this.taskDate;
	}

	public void setTaskDate(Date taskDate) {
		this.taskDate = taskDate;
	}

	public Boolean getCreateSuccess() {
		return this.createSuccess;
	}

	public void setCreateSuccess(Boolean createSuccess) {
		this.createSuccess = createSuccess;
	}

	public Boolean getRunSuccess() {
		return this.runSuccess;
	}

	public void setRunSuccess(Boolean runSuccess) {
		this.runSuccess = runSuccess;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
