package com.sw.bi.scheduler.model;

// Generated 2011-12-19 14:42:39 by Hibernate Tools 3.4.0.CR1


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonSetter;

import java.util.Date;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable, AuthenticationUserGroup {

	private Long userId;
	private String userName;
	private String realName;
	private String passwd;
	private String email;
	private String mobilePhone;
	private int status;
	private boolean isAdmin;
	private String comments;
	private int userType;
	private Date createTime;
	private Date updateTime;
	private UserGroup userGroup;
	@JsonIgnore
	private Set<Role> roles = new LinkedHashSet<Role>();

	public User() {}

	public User(Long userId, String userName, String passwd, String email, int status, boolean isAdmin, Date createTime) {
		this.userId = userId;
		this.userName = userName;
		this.passwd = passwd;
		this.email = email;
		this.status = status;
		this.isAdmin = isAdmin;
		this.createTime = createTime;
	}

	public User(Long userId, String userName, String passwd, String email, String mobilePhone, int status, boolean isAdmin, String comments, Date createTime, Date updateTime) {
		this.userId = userId;
		this.userName = userName;
		this.passwd = passwd;
		this.email = email;
		this.mobilePhone = mobilePhone;
		this.status = status;
		this.isAdmin = isAdmin;
		this.comments = comments;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	@JsonIgnore
	public String getPasswd() {
		return this.passwd;
	}

	@JsonSetter
	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public boolean getIsAdmin() {
		return isAdmin;
	}

	public void setIsAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public int getUserType() {
		return userType;
	}

	public void setUserType(int userType) {
		this.userType = userType;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Set<Role> getRoles() {
		return roles;
	}

	@JsonSetter
	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	public UserGroup getUserGroup() {
		return userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

	public String getRoleNames() {
		StringBuilder roleNames = new StringBuilder();

		for (Role role : this.getRoles()) {
			if (roleNames.length() > 0) {
				roleNames.append(",");
			}

			roleNames.append(role.getRoleName());
		}

		return roleNames.toString();
	}

	@Override
	public String getEntityName() {
		return "用户";
	}

	@Override
	public String getLoggerName() {
		return this.getRealName() + "(" + this.getUserName() + " - " + this.getUserId() + ")";
	}

}
